
volumes:
  redis_data:
    name: redis_data
  rabbitmq_data:
    name: rabbitmq_data

services:
  scraper-api:
    build: .
    container_name: web-scraper-api
    command: uvicorn webscraper.app:create_app --host 0.0.0.0 --port 8000 --factory
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"
    # volumes:
    #     - rabbitmq_data:/var/lib/rabbitmq 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  worker:
    build: .
    command: python -m webscraper.scripts.run_worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always